<?php
namespace App\Services;

use App\Models\File;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Auth;

class FileService
{

    public static function saveUploadedFile(UploadedFile $file, $location, $name = null){

        if($name){
            // upload with custom name
            $filename = $name . "." . $file->getClientOriginalExtension();
            $imagePath = $file->storeAs($location, $filename);
        }
        else{
            $filename = '';
            // upload with autogenerated name
            $imagePath = $file->store($location);
        }

        // save into DB
        $newFile = new File();
        $newFile->name = $filename;
        $newFile->type = $file->getClientMimeType();
        $newFile->size = $file->getSize();
        $newFile->path = $imagePath;
        $newFile->created_by = Auth::id();
        $newFile->save();

        return $newFile;

    }

}